### ISSUE TITLE
null value in column "to_address"

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-server#27]
```
[2014-08-09T16:11:47.946Z] ERROR: lamassu-server/27824 on ssustage3: null value in column "to_address" violates not-null constraint
    error: null value in column "to_address" violates not-null constraint
        at Connection.parseE (/root/tmp/lamassu-server/node_modules/pg/lib/connection.js:561:11)
        at Connection.parseMessage (/root/tmp/lamassu-server/node_modules/pg/lib/connection.js:390:17)
        at null.<anonymous> (/root/tmp/lamassu-server/node_modules/pg/lib/connection.js:98:18)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:748:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:410:10)
        at emitReadable (_stream_readable.js:406:5)
        at readableAddChunk (_stream_readable.js:168:9)
        at Socket.Readable.push (_stream_readable.js:130:10)
```

**Comment by naconner** [comment]
No longer relevant with v3.
