### ISSUE TITLE
Error still thrown after running lamassu-disable-trading, requiring lamassu-server restart

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-server#40]
`lamassu-server@1.0.0 | lamassu-machine@0.2.19 | lamassu-bitstamp@1.0.0`

Began to collect server [**logs**](https://gist.github.com/naconner/19d97b67f14c014546f5), then enabled trading in admin panel with incorrect credentials.

No change to machine (unlike Sorry/Down screen as expected with prior versions.)

Server logs showed with each poll request:
```
[2014-08-29T20:49:11.519Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: poll request from: 0C:E8:07:B0:2F:80:73:20:39:9F:73:6C:E4:CC:C0:BD:B9:72:D4:9F
[2014-08-29T20:49:14.869Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: checking for trades
[2014-08-29T20:49:14.869Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: consolidated:  {"currency":"USD","satoshis":0}
[2014-08-29T20:49:14.870Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: rejecting 0 trade
```
After conducting transaction, each poll request returned, 'API Key Not Found':
```
[2014-08-29T20:49:36.808Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: poll request from: 0C:E8:07:B0:2F:80:73:20:39:9F:73:6C:E4:CC:C0:BD:B9:72:D4:9F
[2014-08-29T20:49:39.890Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: checking for trades
[2014-08-29T20:49:39.890Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: consolidated:  {"currency":"USD","satoshis":196000}
[2014-08-29T20:49:39.891Z] DEBUG: lamassu-server/9897 on lamassu-bitcoind: making a trade: 0.00196
[2014-08-29T20:49:41.485Z] ERROR: lamassu-server/9897 on lamassu-bitcoind: 0: A; 1: P; 2: I; 3:  ; 4: k; 5: e; 6: y; 7:  ; 8: n; 9: o; 10: t; 11:  ; 12: f; 13: o; 14: u; 15: n; 16: d
    Error: 0: A; 1: P; 2: I; 3:  ; 4: k; 5: e; 6: y; 7:  ; 8: n; 9: o; 10: t; 11:  ; 12: f; 13: o; 14: u; 15: n; 16: d
        at processError (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/lib/trader.js:77:10)
        at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/lib/trader.js:89:23
        at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/lib/common.js:52:5
        at /usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/node_modules/wreck/lib/index.js:341:20
        at finish (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/node_modules/wreck/lib/index.js:220:16)
        at wrapped (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/node_modules/wreck/node_modules/hoek/lib/index.js:560:20)
        at onReaderFinish (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitstamp/node_modules/wreck/lib/index.js:254:16)
        at g (events.js:180:16)
        at EventEmitter.emit (events.js:117:20)
        at finishMaybe (_stream_writable.js:360:12)
```
Ran `lamassu-disable-trading` script, but still threw above error with each poll request.

Only after running `restart lamassu-server`, was error no longer received.

Possibly related to https://github.com/lamassu/lamassu-server/issues/38 and https://github.com/lamassu/lamassu-server/issues/39

**Comment by naconner** [comment]
Looks like this has been handled in the latest versions. Closing.
